const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('heroWindow', {
  minimize: () => ipcRenderer.send('window:minimize'),
  close: () => ipcRenderer.send('window:close'),
  togglePin: () => ipcRenderer.send('window:toggle-pin'),
  toggleCatalog: () => ipcRenderer.send('catalog:toggle'),
  notifyTheme: (name) => ipcRenderer.send('catalog:theme-from-main', name),
  dockToCorner: () => ipcRenderer.send('window:dock-to-corner'),
  getPinState: () => ipcRenderer.invoke('window:get-pin-state'),
  onPinStateChanged: (callback) => ipcRenderer.on('pin-state-changed', (_event, pinned) => callback(pinned)),
  notifyMoneyIn: (amount, name, type) => ipcRenderer.send('money:in', { amount, name, type }),
  notifyPbDisconnected: (downMinutes) => ipcRenderer.send('pb:disconnected-warning', downMinutes),
  pollMissedPushes: (token, sinceTs) => ipcRenderer.invoke('pb:poll-missed', { token, sinceTs }),
  onForceReconnect: (callback) => ipcRenderer.on('force-reconnect-pushbullet', () => callback()),
  onNetworkChanged: (callback) => ipcRenderer.on('network-changed', (_event, info) => callback(info)),
  setInboxConfig: (cfg) => ipcRenderer.send('inbox:config', cfg),
  inboxAck: (key) => ipcRenderer.send('inbox:ack', { key }),
  firewallCheck: () => ipcRenderer.invoke('inbox:firewall-check'),
  firewallAdd: (port) => ipcRenderer.invoke('inbox:firewall-add', port),
  onInboxEvent: (callback) => ipcRenderer.on('inbox:event', (_event, evt) => callback(evt)),
  onInboxStatus: (callback) => ipcRenderer.on('inbox:status', (_event, status) => callback(status)),
  onInboxLog: (callback) => ipcRenderer.on('inbox:log', (_event, m) => callback(m)),
  onInboxCursor: (callback) => ipcRenderer.on('inbox:cursor', (_event, c) => callback(c)),
  onInboxBackfill: (callback) => ipcRenderer.on('inbox:fb-backfill', (_event, r) => callback(r)),
  onPaymentEvent: (callback) => ipcRenderer.on('payment:event', (_event, payload) => callback(payload)),
  onRelayStatus: (callback) => ipcRenderer.on('relay:status', (_event, status) => callback(status)),
  getRelayInfo: () => ipcRenderer.invoke('relay:get-info'),
  enterMini: () => ipcRenderer.send('window:enter-mini'),
  exitMini: () => ipcRenderer.send('window:exit-mini'),
  dragMiniStart: () => ipcRenderer.send('window:mini-drag-start'),
  dragMiniMove: () => ipcRenderer.send('window:mini-drag-move'),
  dragMiniEnd: () => ipcRenderer.send('window:mini-drag-end'),
  onModeChanged: (callback) => ipcRenderer.on('mode-changed', (_event, mode) => callback(mode)),
  onModeTransition: (callback) => ipcRenderer.on('mode-transition', (_event, payload) => callback(payload)),
  collapseReady: () => ipcRenderer.send('window:collapse-ready'),
  setBackgroundColor: (hex) => ipcRenderer.send('ui:bg-color', hex),
  rawPrint: (rect) => ipcRenderer.invoke('print:raw', rect),
  printCaptureSlice: (jobId, rect) => ipcRenderer.invoke('print:capture-slice', { jobId, rect })
});
